import{Router,useHref,useNavigate,useLocation,useResolvedPath,useBlocker}from'react-router';import{createBrowserHistory,createHashHistory,createPath}from'history';import PropTypes from'prop-types';import{useRef,unstable_useTransition,useReducer,useLayoutEffect,createElement,forwardRef,useCallback,useMemo}from'react';export{MemoryRouter,Navigate,Outlet,Route,Router,Routes,createRoutesFromArray,createRoutesFromChildren,generatePath,matchPath,matchRoutes,resolvePath,useBlocker,useHref,useInRouterContext,useLocation,useLocationPending,useMatch,useNavigate,useOutlet,useParams,useResolvedPath,useRoutes}from'react-router';function n(){n=Object.assign||function(a){for(var c=1;c<arguments.length;c++){var b=arguments[c],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(a[d]=b[d])}return a};return n.apply(this,arguments)}function p(a,c){if(null==a)return{};var b={},d=Object.keys(a),f;for(f=0;f<d.length;f++){var e=d[f];0<=c.indexOf(e)||(b[e]=a[e])}return b}
function q(a,c){if(a){if("string"===typeof a)return r(a,c);var b=Object.prototype.toString.call(a).slice(8,-1);"Object"===b&&a.constructor&&(b=a.constructor.name);if("Map"===b||"Set"===b)return Array.from(b);if("Arguments"===b||/^(?:Ui|I)nt(?:8|16|32)(?:Clamped)?Array$/.test(b))return r(a,c)}}function r(a,c){if(null==c||c>a.length)c=a.length;for(var b=0,d=Array(c);b<c;b++)d[b]=a[b];return d}
function t(a){var c=0;if("undefined"===typeof Symbol||null==a[Symbol.iterator]){if(Array.isArray(a)||(a=q(a)))return function(){return c>=a.length?{done:!0}:{done:!1,value:a[c++]}};throw new TypeError("Invalid attempt to iterate non-iterable instance.\nIn order to be iterable, non-array objects must have a [Symbol.iterator]() method.");}c=a[Symbol.iterator]();return c.next.bind(c)}function v(a,c){if(!a){"undefined"!==typeof console&&console.warn(c);try{throw Error(c);}catch(b){}}}
function w(a){var c=a.children,b=a.timeoutMs;b=void 0===b?5E3:b;var d=a.window;a=useRef();null==a.current&&(a.current=createBrowserHistory({window:d}));b=unstable_useTransition({timeoutMs:b});var f=b[0];b=b[1];var e=a.current;a=useReducer(function(a,b){return b},{action:e.action,location:e.location});d=a[0];var g=a[1];useLayoutEffect(function(){return e.listen(function(a){f(function(){g(a)})})},[e,f]);return createElement(Router,{children:c,action:d.action,location:d.location,navigator:e,pending:b})}
"production"!==process.env.NODE_ENV&&(w.displayName="BrowserRouter",w.propTypes={children:PropTypes.node,timeoutMs:PropTypes.number,window:PropTypes.object});
function x(a){var c=a.children,b=a.timeoutMs;b=void 0===b?5E3:b;var d=a.window;a=useRef();null==a.current&&(a.current=createHashHistory({window:d}));b=unstable_useTransition({timeoutMs:b});var f=b[0];b=b[1];var e=a.current;a=useReducer(function(a,b){return b},{action:e.action,location:e.location});d=a[0];var g=a[1];useLayoutEffect(function(){return e.listen(function(a){f(function(){g(a)})})},[e,f]);return createElement(Router,{children:c,action:d.action,location:d.location,navigator:e,pending:b})}
"production"!==process.env.NODE_ENV&&(x.displayName="HashRouter",x.propTypes={children:PropTypes.node,timeoutMs:PropTypes.number,window:PropTypes.object});
var y=forwardRef(function(a,c){var b=a.onClick,d=a.replace,f=void 0===d?!1:d,e=a.state,g=a.target,m=a.to;a=p(a,["onClick","replace","state","target","to"]);d=useHref(m);var k=useNavigate(),u=useLocation(),h=useResolvedPath(m);return createElement("a",Object.assign({},a,{href:d,onClick:function(a){b&&b(a);a.defaultPrevented||0!==a.button||g&&"_self"!==g||a.metaKey||a.altKey||a.ctrlKey||a.shiftKey||(a.preventDefault(),a=!!f||createPath(u)===createPath(h),k(m,{replace:a,state:e}))},ref:c,target:g}))});
"production"!==process.env.NODE_ENV&&(y.displayName="Link",y.propTypes={onClick:PropTypes.func,replace:PropTypes.bool,state:PropTypes.object,target:PropTypes.string,to:PropTypes.oneOfType([PropTypes.string,PropTypes.shape({pathname:PropTypes.string,search:PropTypes.string,hash:PropTypes.string})]).isRequired});
var z=forwardRef(function(a,c){var b=a["aria-current"],d=void 0===b?"page":b;b=a.activeClassName;var f=void 0===b?"active":b;b=a.activeStyle;var e=a.caseSensitive,g=void 0===e?!1:e;e=a.className;var m=void 0===e?"":e;e=a.end;var k=void 0===e?!1:e,u=a.style;e=a.to;a=p(a,"aria-current activeClassName activeStyle caseSensitive className end style to".split(" "));var h=useLocation(),l=useResolvedPath(e);h=h.pathname;l=l.pathname;g||(h=h.toLowerCase(),l=l.toLowerCase());d=(g=k?h===l:h.startsWith(l))?d:
void 0;f=[m,g?f:null].filter(Boolean).join(" ");b=n({},u,{},g?b:null);return createElement(y,Object.assign({},a,{"aria-current":d,className:f,ref:c,style:b,to:e}))});
"production"!==process.env.NODE_ENV&&(z.displayName="NavLink",z.propTypes=n({},y.propTypes,{"aria-current":PropTypes.oneOf("page step location date time true".split(" ")),activeClassName:PropTypes.string,activeStyle:PropTypes.object,className:PropTypes.string,style:PropTypes.object,to:PropTypes.oneOfType([PropTypes.string,PropTypes.shape({pathname:PropTypes.string,search:PropTypes.string,hash:PropTypes.string})]).isRequired}));function A(a){B(a.message,a.when);return null}
"production"!==process.env.NODE_ENV&&(A.displayName="Prompt",A.propTypes={message:PropTypes.string,when:PropTypes.bool});function B(a,c){void 0===c&&(c=!0);var b=useCallback(function(b){window.confirm(a)&&b.retry()},[a]);useBlocker(b,c)}function C(a){void 0===a&&(a="");return new URLSearchParams("string"===typeof a||Array.isArray(a)||a instanceof URLSearchParams?a:Object.keys(a).reduce(function(c,b){var d=a[b];return c.concat(Array.isArray(d)?d.map(function(a){return[b,a]}):[[b,d]])},[]))}


function useSearchParams(a){"production"!==process.env.NODE_ENV?v("undefined"!==typeof URLSearchParams,"You cannot use the `useSearchParams` hook in a browser that does not support the URLSearchParams API. If you need to support Internet Explorer 11, we recommend you load a polyfill such as https://github.com/ungap/url-search-params\n\nIf you're unsure how to load polyfills, we recommend you check out https://polyfill.io/v3/ which provides some recommendations about how to load polyfills only for users that need them, instead of for every user."):void 0;
var c=useRef(C(a)),b=useLocation();a=useMemo(function(){function a(){var a=k.value;d.has(a)||c.current.getAll(a).forEach(function(b){d.append(a,b)})}for(var d=C(b.search),f=t(c.current.keys()),k;!(k=f()).done;)a();return d},[b.search]);var d=useNavigate(),f=useCallback(function(a,b){d("?"+C(a),b)},[d]);return[a,f]};export{w as BrowserRouter,x as HashRouter,y as Link,z as NavLink,A as Prompt,C as createSearchParams,B as usePrompt,useSearchParams}
//# sourceMappingURL=index.js.map
