import{createMemoryHistory,Action,parsePath}from'history';import PropTypes from'prop-types';import{createContext,useRef,unstable_useTransition,useReducer,useLayoutEffect,createElement,useContext,useEffect,useMemo,useCallback,Children,isValidElement,Fragment}from'react';function h(){h=Object.assign||function(a){for(var b=1;b<arguments.length;b++){var c=arguments[b],d;for(d in c)Object.prototype.hasOwnProperty.call(c,d)&&(a[d]=c[d])}return a};return h.apply(this,arguments)}var k="production"!==process.env.NODE_ENV?function(a){return Object.freeze(a)}:function(a){return a};function l(a,b){if(!a)throw Error(b);}function m(a,b){if(!a){"undefined"!==typeof console&&console.warn(b);try{throw Error(b);}catch(c){}}}var p={};
function r(a,b,c){b||p[a]||(p[a]=!0,"production"!==process.env.NODE_ENV?m(!1,c):void 0)}var t=createContext({pending:!1,static:!1});"production"!==process.env.NODE_ENV&&(t.displayName="Location");var v=createContext({outlet:null,params:k({}),pathname:"",route:null});"production"!==process.env.NODE_ENV&&(v.displayName="Route");
function x(a){var b=a.children,c=a.initialEntries,d=a.initialIndex;a=a.timeoutMs;var e=void 0===a?5E3:a;a=useRef();null==a.current&&(a.current=createMemoryHistory({initialEntries:c,initialIndex:d}));c=unstable_useTransition({timeoutMs:e});var g=c[0];c=c[1];var f=a.current;d=useReducer(function(a,c){return c},{action:f.action,location:f.location});a=d[0];var w=d[1];useLayoutEffect(function(){return f.listen(function(a){g(function(){w(a)})})},[f,g]);return createElement(y,{children:b,action:a.action,
location:a.location,navigator:f,pending:c})}"production"!==process.env.NODE_ENV&&(x.displayName="MemoryRouter",x.propTypes={children:PropTypes.node,initialEntries:PropTypes.arrayOf(PropTypes.oneOfType([PropTypes.string,PropTypes.shape({pathname:PropTypes.string,search:PropTypes.string,hash:PropTypes.string,state:PropTypes.object,key:PropTypes.string})])),initialIndex:PropTypes.number,timeoutMs:PropTypes.number});
function z(a){var b=a.to,c=a.replace,d=a.state;A()?void 0:"production"!==process.env.NODE_ENV?l(!1,"<Navigate> may be used only in the context of a <Router> component."):l(!1);"production"!==process.env.NODE_ENV?m(!useContext(t).static,"<Navigate> must not be used on the initial render in a <StaticRouter>. This is a no-op, but you should modify your code so the <Navigate> is only ever rendered in response to some user interaction or state change."):void 0;var e=B();useEffect(function(){e(b,{replace:c,
state:d})});return null}"production"!==process.env.NODE_ENV&&(z.displayName="Navigate",z.propTypes={to:PropTypes.oneOfType([PropTypes.string,PropTypes.shape({pathname:PropTypes.string,search:PropTypes.string,hash:PropTypes.string})]).isRequired,replace:PropTypes.bool,state:PropTypes.object});function C(){return D()}"production"!==process.env.NODE_ENV&&(C.displayName="Outlet",C.propTypes={});function E(a){a=a.element;return void 0===a?createElement(C,null):a}
"production"!==process.env.NODE_ENV&&(E.displayName="Route",E.propTypes={caseSensitive:PropTypes.bool,children:PropTypes.node,element:PropTypes.element,path:PropTypes.string});
function y(a){var b=a.children;b=void 0===b?null:b;var c=a.action;c=void 0===c?Action.Pop:c;var d=a.location,e=a.navigator,g=a.pending;g=void 0===g?!1:g;a=a.static;a=void 0===a?!1:a;A()?"production"!==process.env.NODE_ENV?l(!1,"You cannot render a <Router> inside another <Router>. You never need more than one."):l(!1):void 0;return createElement(t.Provider,{children:b,value:{action:c,location:d,navigator:e,pending:g,static:a}})}
"production"!==process.env.NODE_ENV&&(y.displayName="Router",y.propTypes={children:PropTypes.node,action:PropTypes.oneOf(["POP","PUSH","REPLACE"]),location:PropTypes.object.isRequired,navigator:PropTypes.shape({createHref:PropTypes.func.isRequired,push:PropTypes.func.isRequired,replace:PropTypes.func.isRequired,go:PropTypes.func.isRequired,block:PropTypes.func.isRequired}).isRequired,pending:PropTypes.bool,static:PropTypes.bool});
function F(a){var b=a.basename;b=void 0===b?"":b;a=G(a.children);return H(a,b)}"production"!==process.env.NODE_ENV&&(F.displayName="Routes",F.propTypes={basename:PropTypes.string,children:PropTypes.node});function A(){return null!=useContext(t).location}function I(){A()?void 0:"production"!==process.env.NODE_ENV?l(!1,"useLocation() may be used only in the context of a <Router> component."):l(!1);return useContext(t).location}
function B(){A()?void 0:"production"!==process.env.NODE_ENV?l(!1,"useNavigate() may be used only in the context of a <Router> component."):l(!1);var a=useContext(t),b=a.navigator,c=a.pending,d=useContext(v).pathname,e=useRef(!1);useEffect(function(){e.current=!0});return useCallback(function(a,f){void 0===f&&(f={});e.current?"number"===typeof a?b.go(a):(a=J(a,d),(f.replace||c?b.replace:b.push)(a,f.state)):"production"!==process.env.NODE_ENV?m(!1,"You should call navigate() in a useEffect, not when your component is first rendered."):
void 0},[b,d,c])}function D(){return useContext(v).outlet}function K(a){var b=useContext(v).pathname;return useMemo(function(){return J(a,b)},[a,b])}
function H(a,b){void 0===b&&(b="");var c=useContext(v),d=c.route,e=c.pathname,g=c.params;"production"!==process.env.NODE_ENV&&(c=d&&d.path,r(e,!d||d.path.endsWith("*"),'You rendered descendant <Routes> (or called `useRoutes`) at "'+e+'" (under <Route path="'+(c+'">) but the parent route path has no trailing "*". This means if you navigate deeper, the parent won\'t match anymore and therefore the child routes will never render.\n\nPlease change the parent <Route path="')+(c+'"> to <Route path="'+c+
'/*">.')));b=b?L([e,b]):e;d=useRef();var f=I();e=useMemo(function(){return M(a,f,b)},[f,a,b]);if(!e)return null;d.current!==f&&(d.current=f,e.forEach(function(a,c){var b=a.route;a=a.params;return b.preload&&b.preload(a,f,c)}));return e.reduceRight(function(a,c){var d=c.pathname,e=c.route;return createElement(v.Provider,{children:e.element,value:{outlet:a,params:k(h({},g,{},c.params)),pathname:L([b,d]),route:e}})},null)}
function N(a){return a.map(function(a){var c={path:a.path||"/",caseSensitive:!0===a.caseSensitive,element:a.element||createElement(C,null),preload:a.preload};a.children&&(c.children=N(a.children));return c})}
function G(a){var b=[];Children.forEach(a,function(a){if(isValidElement(a))if(a.type===Fragment)b.push.apply(b,G(a.props.children));else{var c={path:a.props.path||"/",caseSensitive:!0===a.props.caseSensitive,element:a,preload:a.props.preload};a.props.children&&(a=G(a.props.children),a.length&&(c.children=a));b.push(c)}});return b}
function M(a,b,c){void 0===c&&(c="");"string"===typeof b&&(b=parsePath(b));b=b.pathname||"/";if(c)if(c=c.replace(/^\/*/,"/").replace(/\/+$/,""),b.startsWith(c))b=b===c?"/":b.slice(c.length);else return null;a=O(a);P(a);var d=null;for(c=0;null==d&&c<a.length;++c)a:{d=b;for(var e=a[c][1],g="/",f={},w=[],n=0;n<e.length;++n){var q=e[n],u="/"===g?d:d.slice(g.length)||"/";u=Q({path:q.path,caseSensitive:q.caseSensitive,end:n===e.length-1},u);if(!u){d=null;break a}g=L([g,u.pathname]);f=h({},f,{},u.params);
w.push({route:q,pathname:g,params:k(f)})}d=w}return d}function O(a,b,c,d,e){void 0===b&&(b=[]);void 0===c&&(c="");void 0===d&&(d=[]);void 0===e&&(e=[]);a.forEach(function(a,f){var g=L([c,a.path]),n=d.concat(a);f=e.concat(f);a.children&&O(a.children,b,g,n,f);b.push([g,n,f])});return b}function P(a){var b=a.reduce(function(a,b){b=b[0];a[b]=R(b);return a},{});S(a,function(a,d){var c=a[2];a=b[a[0]];var g=d[2];d=b[d[0]];return a!==d?d-a:T(c,g)})}var U=/^:\w+$/,V=2,W=1,X=10,Y=-2;
function Z(a){return"*"===a}function R(a){a=a.split("/");var b=a.length;a.some(Z)&&(b+=Y);return a.filter(function(a){return!Z(a)}).reduce(function(a,b){return a+(U.test(b)?V:""===b?W:X)},b)}function T(a,b){return a.length===b.length&&a.slice(0,-1).every(function(a,d){return a===b[d]})?a[a.length-1]-b[b.length-1]:0}function S(a,b){var c=a.slice(0);a.sort(function(a,e){return b(a,e)||c.indexOf(a)-c.indexOf(e)})}
function Q(a,b){"string"===typeof a&&(a={path:a});var c=a;a=c.path;var d=c.caseSensitive;c=c.end;c=aa(a,void 0===d?!1:d,void 0===c?!0:c);d=c[1];c=b.match(c[0]);if(!c)return null;b=c[1];var e=c.slice(2);d=d.reduce(function(a,b,c){c=e[c];try{var d=decodeURIComponent(c.replace(/\+/g," "))}catch(q){"production"!==process.env.NODE_ENV?m(!1,'The value for the URL param "'+b+'" will not be decoded because the string "'+(c+'" is a malformed URL segment. This is probably due to a bad percent encoding (')+
(q+").")):void 0,d=c}a[b]=d;return a},{});return{path:a,pathname:b,params:d}}function aa(a,b,c){var d=[],e="^("+a.replace(/^\/*/,"/").replace(/\/?\*?$/,"").replace(/[\\.*+^$?{}|()[\]]/g,"\\$&").replace(/:(\w+)/g,function(a,b){d.push(b);return"([^\\/]+)"})+")";a.endsWith("*")?(a.endsWith("/*")&&(e+="\\/?"),d.push("*"),e+="(.*)"):c&&(e+="\\/?");c&&(e+="$");return[new RegExp(e,b?void 0:"i"),d]}
function J(a,b){void 0===b&&(b="/");var c="string"===typeof a?parsePath(a):a;a=c.pathname;var d=c.search;d=void 0===d?"":d;c=c.hash;c=void 0===c?"":c;return{pathname:a?ba(a,a.startsWith("/")?"/":b):b,search:d,hash:c}}function L(a){return a.join("/").replace(/\/\/+/g,"/")}function ba(a,b){var c=b.replace(/\/+$/,"").replace(/\/\/+/g,"/").split("/");a.replace(/\/\/+/g,"/").split("/").forEach(function(a){".."===a?1<c.length&&c.pop():"."!==a&&c.push(a)});return 1<c.length?L(c):"/"}
function generatePath(a,b){void 0===b&&(b={});return a.replace(/:(\w+)/g,function(a,d){null==b[d]?"production"!==process.env.NODE_ENV?l(!1,'Missing ":'+d+'" param'):l(!1):void 0;return b[d]}).replace(/\/*\*$/,function(){return null==b["*"]?"":b["*"].replace(/^\/*/,"/")})};
function useBlocker(a,b){void 0===b&&(b=!0);A()?void 0:"production"!==process.env.NODE_ENV?l(!1,"useBlocker() may be used only in the context of a <Router> component."):l(!1);var c=useContext(t).navigator;useEffect(function(){if(b){var d=c.block(function(b){var c=h({},b,{retry:function(){d();b.retry()}});a(c)});return d}},[c,a,b])};
function useHref(a){A()?void 0:"production"!==process.env.NODE_ENV?l(!1,"useHref() may be used only in the context of a <Router> component."):l(!1);var b=useContext(t).navigator;a=K(a);return b.createHref(a)};function useLocationPending(){return useContext(t).pending};
function useMatch(a){A()?void 0:"production"!==process.env.NODE_ENV?l(!1,"useMatch() may be used only in the context of a <Router> component."):l(!1);var b=I();return Q(a,b.pathname)};function useParams(){return useContext(v).params};
function useRoutes(a,b){void 0===b&&(b="");A()?void 0:"production"!==process.env.NODE_ENV?l(!1,"useRoutes() may be used only in the context of a <Router> component."):l(!1);var c=useMemo(function(){return N(a)},[a]);return H(c,b)};export{x as MemoryRouter,z as Navigate,C as Outlet,E as Route,y as Router,F as Routes,N as createRoutesFromArray,G as createRoutesFromChildren,generatePath,Q as matchPath,M as matchRoutes,J as resolvePath,useBlocker,useHref,A as useInRouterContext,I as useLocation,useLocationPending,useMatch,B as useNavigate,D as useOutlet,useParams,K as useResolvedPath,useRoutes}
//# sourceMappingURL=index.js.map
