"use strict";

const interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault").default;
const interopRequireWildcard = require("@babel/runtime/helpers/interopRequireWildcard").default;

Object.defineProperty(exports, "__esModule", { value: true });

const componentsMap = {
  colors: './colors',
  Accordion: './Accordion',
  AccordionActions: './AccordionActions',
  AccordionDetails: './AccordionDetails',
  AccordionSummary: './AccordionSummary',
  Alert: './Alert',
  AlertTitle: './AlertTitle',
  AppBar: './AppBar',
  Autocomplete: './Autocomplete',
  Avatar: './Avatar',
  AvatarGroup: './AvatarGroup',
  Backdrop: './Backdrop',
  Badge: './Badge',
  BottomNavigation: './BottomNavigation',
  BottomNavigationAction: './BottomNavigationAction',
  Box: './Box',
  Breadcrumbs: './Breadcrumbs',
  Button: './Button',
  ButtonBase: './ButtonBase',
  ButtonGroup: './ButtonGroup',
  Card: './Card',
  CardActionArea: './CardActionArea',
  CardActions: './CardActions',
  CardContent: './CardContent',
  CardHeader: './CardHeader',
  CardMedia: './CardMedia',
  Checkbox: './Checkbox',
  Chip: './Chip',
  CircularProgress: './CircularProgress',
  ClickAwayListener: './ClickAwayListener',
  Collapse: './Collapse',
  Container: './Container',
  CssBaseline: './CssBaseline',
  darkScrollbar: './darkScrollbar',
  Dialog: './Dialog',
  DialogActions: './DialogActions',
  DialogContent: './DialogContent',
  DialogContentText: './DialogContentText',
  DialogTitle: './DialogTitle',
  Divider: './Divider',
  Drawer: './Drawer',
  Fab: './Fab',
  Fade: './Fade',
  FilledInput: './FilledInput',
  FormControl: './FormControl',
  FormControlLabel: './FormControlLabel',
  FormGroup: './FormGroup',
  FormHelperText: './FormHelperText',
  FormLabel: './FormLabel',
  Grid: './Grid',
  Grid2: './Grid2',
  Grow: './Grow',
  Hidden: './Hidden',
  Icon: './Icon',
  IconButton: './IconButton',
  ImageList: './ImageList',
  ImageListItem: './ImageListItem',
  ImageListItemBar: './ImageListItemBar',
  Input: './Input',
  InputAdornment: './InputAdornment',
  InputBase: './InputBase',
  InputLabel: './InputLabel',
  LinearProgress: './LinearProgress',
  Link: './Link',
  List: './List',
  ListItem: './ListItem',
  ListItemAvatar: './ListItemAvatar',
  ListItemButton: './ListItemButton',
  ListItemIcon: './ListItemIcon',
  ListItemSecondaryAction: './ListItemSecondaryAction',
  ListItemText: './ListItemText',
  ListSubheader: './ListSubheader',
  Menu: './Menu',
  MenuItem: './MenuItem',
  MenuList: './MenuList',
  MobileStepper: './MobileStepper',
  Modal: './Modal',
  NativeSelect: './NativeSelect',
  NoSsr: './NoSsr',
  OutlinedInput: './OutlinedInput',
  Pagination: './Pagination',
  PaginationItem: './PaginationItem',
  Paper: './Paper',
  Popover: './Popover',
  Popper: './Popper',
  Portal: './Portal',
  Radio: './Radio',
  RadioGroup: './RadioGroup',
  Rating: './Rating',
  ScopedCssBaseline: './ScopedCssBaseline',
  Select: './Select',
  Skeleton: './Skeleton',
  Slide: './Slide',
  Slider: './Slider',
  Snackbar: './Snackbar',
  SnackbarContent: './SnackbarContent',
  SpeedDial: './SpeedDial',
  SpeedDialAction: './SpeedDialAction',
  SpeedDialIcon: './SpeedDialIcon',
  Stack: './Stack',
  Step: './Step',
  StepButton: './StepButton',
  StepConnector: './StepConnector',
  StepContent: './StepContent',
  StepIcon: './StepIcon',
  StepLabel: './StepLabel',
  Stepper: './Stepper',
  SvgIcon: './SvgIcon',
  SwipeableDrawer: './SwipeableDrawer',
  Switch: './Switch',
  Tab: './Tab',
  Table: './Table',
  TableBody: './TableBody',
  TableCell: './TableCell',
  TableContainer: './TableContainer',
  TableFooter: './TableFooter',
  TableHead: './TableHead',
  TablePagination: './TablePagination',
  TableRow: './TableRow',
  TableSortLabel: './TableSortLabel',
  Tabs: './Tabs',
  TabScrollButton: './TabScrollButton',
  TextField: './TextField',
  TextareaAutosize: './TextareaAutosize',
  ToggleButton: './ToggleButton',
  ToggleButtonGroup: './ToggleButtonGroup',
  Toolbar: './Toolbar',
  Tooltip: './Tooltip',
  Typography: './Typography',
  useMediaQuery: './useMediaQuery',
  usePagination: './usePagination',
  useScrollTrigger: './useScrollTrigger',
  Zoom: './Zoom',
  useAutocomplete: './useAutocomplete',
  GlobalStyles: './GlobalStyles',
  unstable_composeClasses: '@mui/utils',
  generateUtilityClass: './generateUtilityClass',
  generateUtilityClasses: './generateUtilityClasses',
  Unstable_TrapFocus: './Unstable_TrapFocus',
  version: './version'
};

// Import and define properties for each component
for (const [exportName, path] of Object.entries(componentsMap)) {
  Object.defineProperty(exports, exportName, {
    enumerable: true,
    get: function() {
      // Handle wildcard imports separately
      const module = exportName === "colors" || exportName === "GlobalStyles" ? interopRequireWildcard(require(path)) : interopRequireDefault(require(path)).default;
      return module;
    }
  });
}
