train:
  gen:
    data_pth: dataset/apps_gen_train.pkl
  human:
    data_pth: dataset/apps_hum_train.pkl

test:
  gen:
      data_pth: dataset/apps_gen_test.pkl
  human:
      data_pth: dataset/apps_hum_test.pkl