train:
  gen:
    data_pth: dataset/all_gen_train_prompt_split.pkl
    domain:
      - csn
      - humaneval
    temp:
      - 1.0
    top_p:
      - 1.0
  human:
    data_pth: dataset/all_human_train_prompt_split.pkl
    domain:
      - csn
      - appx


test:
  gen:
    data_pth: dataset/all_gen_test_prompt_split.pkl
    domain:
      - csn
      - humaneval
  human:
    data_pth: dataset/all_human_test_prompt_split.pkl
    domain:
      - csn
      - appx