train:
  gen:
    data_pth: dataset/all_gen_train_prompt_split.pkl
    domain:
      - csn
      - humaneval
    top_k:
      - 200
      - 100
      - 50

  human:
    data_pth: dataset/all_human_train_prompt_split.pkl
    domain:
      - csn
      - appx

test:
  gen:
      data_pth: dataset/all_gen_test_prompt_split.pkl
      domain:
          - csn
          - humaneval
  human:
      data_pth: dataset/all_human_test_prompt_split.pkl
      domain:
          - csn
          - appx