train:
  gen:
    data_pth: dataset/all_gen_train.pkl
    domain:
      - csn
      - humaneval
    temp:
      - 0.5
    top_p:
      - 1.0
  human:
    data_pth: dataset/all_human_train.pkl
    domain:
      - csn
      - appx

test:
  gen:
      data_pth: dataset/all_gen_test.pkl
      domain:
          - csn
          - humaneval
  human:
      data_pth: dataset/all_human_test.pkl
      domain:
          - csn
          - appx