train:
  gen:
    data_pth: dataset/edu_gen_train_prompt_split.pkl
    model_name:
      - codegen-2B-mono
      - code_davinci_002
    temp:
      - 0.2
      - 0.5
      - 0.8
      - 1.0
    top_p:
      - 1.0
      - 0.95
      - 0.9
      - 0.85
  human:
    data_pth: dataset/edu_human_train_prompt_split.pkl
    domain:
      - appx

test:
  gen:
      data_pth: dataset/edu_gen_test_prompt_split.pkl
      model_name:
        - codegen-2B-mono
        - code_davinci_002
  human:
      data_pth: dataset/edu_human_test_prompt_split.pkl
      domain:
          - appx