seed: 44
mode: disabled
tags:
  - bertcls
batch_size: 16
simulate_batch_size: 32
valid_batch_size: 32
train_data_pth: detection_data/train_csn_8k.pkl
valid_data_pth: detection_data/valid_csn_8k.pkl
test_data_pth: detection_data/test_he+csn_6k.pkl
gradient_norm_clip_value: 1.0
n_epoch: 10
decay: 3e-4
lr: 1e-4
warmup: 0.1
device: -1
data:
  mini_dataset: true
  max_input_len: 512
  tokenizer_pth: "microsoft/graphcodebert-base"

model:
  plm_name: "microsoft/graphcodebert-base"
  cls_drop: 0.2
  cls_dim: 768
