seed: 44
valid_batch_size: 32
result_pth: detection_results/test_he+appx_deduplicate_mix_full.pkl
device: -1
load_pth: checkpoints/csn_tempmix_full_code.pt
data:
  mini_dataset: false
  max_input_len: 512
  tokenizer_pth: "microsoft/graphcodebert-base"
  completion_only: true

model:
  plm_name: "microsoft/graphcodebert-base"
  cls_drop: 0.2
  cls_dim: 768

setting:
  test:
    gen:
      data_pth: dataset/all_gen_test.pkl
      domain:
        - csn
        - humaneval
    human:
      data_pth: dataset/all_human_test.pkl
      domain:
        - csn
        - appx